name: teta_widgets
description: Official package of Teta
version: 0.0.8
homepage:
publish_to: builder.teta.so:8888

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
     
  teta_core:
    git:
      url: git@github.com:andreabuttarelli/Teta.git
      path: teta_core
      ref: develop

  # DB & Services
  supabase: ^0.2.14
  supabase_flutter: ^0.2.12
  http:
  github: 
  socket_io_client: ^1.0.1
  dart_airtable: ^1.1.0
  mixpanel_analytics: ^2.1.1

  # Bloc
  flutter_bloc: ^7.3.3
  equatable:

  # Typography & Icons
  google_fonts: ^2.1.0  
  flutter_feather_icons: ^2.0.0+1
  material_design_icons_flutter: ^5.0.6595
  flutter_svg: ^1.0.3
  fluentui_system_icons: ^1.1.158
  font_awesome_flutter_named: ^1.0.1+2
  line_icons: ^2.0.1

  # UI
  hovering: ^1.0.4
  graphview: ^1.1.1
  transition: ^2.0.2
  simple_animations: ^4.0.1
  flutter_colorpicker: ^1.0.3
  multi_split_view: ^1.11.0
  focus_detector: ^2.0.1
  sa3_liquid: ^1.0.1

  # Share & send
  mailto: ^2.0.0
  url_launcher: ^6.0.4
  clipboard: ^0.1.3

  # Widgets
  auth_buttons: ^2.0.4
  lottie: ^1.0.1
  youtube_player_iframe: ^2.0.0
  expandable: ^5.0.1
  custom_refresh_indicator: ^1.0.0
  liquid_swipe: ^2.1.1
  map: ^1.0.0
  latlng: ^0.1.0
  webview_windows: ^0.1.6
  badges: ^2.0.1
  flutter_staggered_grid_view: ^0.4.1
  paged_vertical_calendar: ^1.0.4
  webviewx: ^0.2.1
  tcard: ^1.3.5
  concentric_transition: ^1.0.1+1
  bouncing_widget: ^2.0.0
  camera: ^0.9.4+4

  # Utils
  uuid: ^3.0.4
  archive:
  path_provider: ^2.0.1
  downloads_path_provider: ^0.1.0
  password_strength: ^0.2.0
  nanoid: ^1.0.0
  tinycolor: ^1.0.3
  intl: ^0.17.0
  math_expressions: ^2.1.1
  path_drawing: ^1.0.0
  nil: ^1.1.1
  universal_ui: ^0.0.8
  screenshot: ^1.2.3
  feedback: ^2.0.0
  cryptography: ^2.0.2
  catcher: ^0.6.8
  encrypt: ^5.0.1
  after_layout: ^1.1.0
  recase: ^4.0.0
  flutter_gen:
  version: ^2.0.0
  fast_immutable_collections: ^7.1.3
  enum_to_string: ^2.0.1
  flutter_automation: ^2.0.0
  download:
  diacritic: ^0.1.3
  flutter_dotenv: ^5.0.2
  cross_file: ^0.3.1+5
  shake: ^2.0.0
  profanity_filter: ^2.0.0
  device_info_plus: ^3.2.1
  file_picker: ^4.4.0
  package_info_plus: ^1.0.4
  cross_connectivity: ^3.0.3
  linked_scroll_controller: ^0.2.0
  just_audio: ^0.9.18
  location: ^4.3.0
  image: ^3.1.0
  msix: ^2.8.17
  geocode: ^1.0.1
  universal_platform: ^1.0.0+1
  freezed_annotation: ^1.1.0
  gap: ^2.0.0

  # Storage
  hive:
  shared_preferences: ^2.0.5

  # Code
  syntax_highlighter: ^0.1.1
  flutter_highlight: ^0.7.0
  dart_style: ^2.0.1

  # Web
  js: ^0.6.3
  flutter_js: ^0.5.0+3

  # Payments
  purchases_flutter: ^3.0.0 

  # Lint
  very_good_analysis: ^2.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  import_sorter: ^4.6.0

dependencies_overrides:
  teta_core:
    path: ../../Teta/teta_core
  mobile_editor:
    path: ../../Teta/mobile_editor

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
