name: teta_widgets
description: Official package of Teta
version: 0.0.2
homepage:
publish_to: builder.teta.so:8888

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
     
  teta_core:
    git:
      url: git@github.com:andreabuttarelli/Teta.git
      path: teta_core
      ref: develop
  supabase: ^0.2.14
  supabase_flutter: ^0.2.12
  flutter_bloc: ^7.3.3
  equatable:
  purchases_flutter: ^3.0.0 
  uuid: ^3.0.4
  flutter_feather_icons: ^2.0.0+1
  hovering: ^1.0.4
  flutter_colorpicker: ^1.0.3
  google_fonts: ^2.1.0  
  syntax_highlighter: ^0.1.1
  flutter_highlight: ^0.7.0
  dart_style: ^2.0.1
  material_design_icons_flutter: ^5.0.6595
  lottie: ^1.0.1
  http:
  transition: ^2.0.2
  expandable: ^5.0.1
  simple_animations: ^4.0.1
  youtube_player_iframe: ^2.0.0
  clipboard: ^0.1.3
  graphview: ^1.1.1
  mailto: ^2.0.0
  url_launcher: ^6.0.4
  archive:
  shared_preferences: ^2.0.5
  path_provider: ^2.0.1
  downloads_path_provider: ^0.1.0
  password_strength: ^0.2.0
  nanoid: ^1.0.0
  tinycolor: ^1.0.3
  intl: ^0.17.0
  github: 
  badges: ^2.0.1
  math_expressions: ^2.1.1
  flutter_svg: ^1.0.3
  path_drawing: ^1.0.0
  nil: ^1.1.1
  universal_ui: ^0.0.8
  screenshot: ^1.2.3
  flutter_staggered_grid_view: ^0.4.1
  hive:
  auth_buttons: ^2.0.4
  feedback: ^2.0.0
  device_info_plus: ^3.2.1
  version: ^2.0.0
  file_picker: ^4.4.0
  package_info_plus: ^1.0.4
  cross_connectivity: ^3.0.3
  fast_immutable_collections: ^7.1.3
  enum_to_string: ^2.0.1
  very_good_analysis: ^2.3.0
  flutter_gen:
  after_layout: ^1.1.0
  recase: ^4.0.0
  custom_refresh_indicator: ^1.0.0
  cryptography: ^2.0.2
  catcher: ^0.6.8
  encrypt: ^5.0.1
  liquid_swipe: ^2.1.1
  flutter_dotenv: ^5.0.2
  socket_io_client: ^1.0.1
  cross_file: ^0.3.1+5
  flutter_automation: ^2.0.0
  map: ^1.0.0
  latlng: ^0.1.0
  js: ^0.6.3
  shake: ^2.0.0
  flutter_js: ^0.5.0+3
  webviewx: ^0.2.1
  diacritic: ^0.1.3
  tcard: ^1.3.5
  concentric_transition: ^1.0.1+1
  bouncing_widget: ^2.0.0
  paged_vertical_calendar: ^1.0.4
  linked_scroll_controller: ^0.2.0
  #code_text_field: ^1.0.2
  camera: ^0.9.4+4
  mixpanel_analytics: ^2.1.1
  just_audio: ^0.9.18
  location: ^4.3.0
  image: ^3.1.0
  flutter_parallax: ^0.1.2
  sa3_liquid: ^1.0.1
  dart_airtable: ^1.1.0
  fluentui_system_icons: ^1.1.158
  fluent_ui: ^3.8.0
  universal_platform: ^1.0.0+1
  freezed_annotation: ^1.1.0
  msix: ^2.8.17
  geocode: ^1.0.1
  download:
  performance: ^0.1.0+1
  focus_detector: ^2.0.1
  profanity_filter: ^2.0.0
  multi_split_view: ^1.11.0
  webview_windows: ^0.1.6
  overlay_tooltip: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
