include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    use_build_context_synchronously: false
    prefer_final_fields: true
    cancel_subscriptions: true
    close_sinks: true
    always_put_required_named_parameters_first: false
    lines_longer_than_80_chars: false
    library_private_types_in_public_api: false